{%set name = "ebooklib" %}
{%set camelName = "EbookLib" %}
{%set version = "0.16" %}
{%set hash_type = "sha256" %}
{%set hash_val = "c6b565009f450b9c610cf009b59d85d43e6c2d6fdf7d0d1c578e03ee37c32f1a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ camelName }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ camelName }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - lxml
    - six

test:
  imports:
    - ebooklib
    - ebooklib.plugins

about:
  home: https://github.com/aerkalov/ebooklib
  license: AGPL 3.0
  license_file: LICENSE.txt
  summary: 'Ebook library which can handle EPUB2/EPUB3 and Kindle format'
  doc_url: https://github.com/aerkalov/ebooklib/wiki
  dev_url: https://github.com/aerkalov/ebooklib

extra:
  recipe-maintainers:
    - pmlandwehr
