travis:
  secure:
    BINSTAR_TOKEN: VomgSzYEPqGuJnmWNU1OtWc56OIbrwxW7rRLrFLwTnx4sPmsO6YQ5IgQXptYD0HvnlLqS1TbwVoJtR/6Ghual+XIQ1xiIqFsK2DveHOg1e6PwmmAfAeDfyI8O6rEvR7pubDKtriZikXTDd/L4Ni1q+AOpbWovxbfIR7xnVm1c+fCShrkuBZKn3aCjaw3G2kV3F+oxqcLP3o95cqZszMvFRQV7UETNzkpfv1pzKaLnBrtIZ/e+1LFM3ANnWlIuIFr2u32GaQIxBwOmrzIlRSDveRbLCo8i8/UQL+esQsOJ1d6RzTIWWUE9J8FtnU6jAYVjRdiRc0uc8l3DmKWgwsq9cg0JOEJ37uyov0xsKIFWpK2DR65npbjGq6V6WiD+ayqRw9vbDwdID9VvaHKSMMdOJh+N3zn/NQRm/Z9GfDjyC5s8I5dX1ZGVkLdMFnUM/p1ysqLs/2bEBcHbQ/6Rha0HoPts3QGhWCP6ZmaUH5c0+68oP/XcoI9E+niVCK64jJjoHpQZdZRENzfc6eTyRi5QimchKBELXaOyqgB/b6Uw/87gNl+Hg1Ru/8XrSSw3sjSaEFQoSeXwyrc2sDPPojensgYTgB6aVeiAdmOd/sYHUIjVe6SeGT2fxGFEBsHBb46lJSq5OPd/ArzASy9U/aauZdj211OFGBe15MjPWfQ7EQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
