travis:
  secure:
    BINSTAR_TOKEN: Crc7XRQJGkbcnXuKMgDXxR3RdkMDvT4yqalmwnJopPcyy9ThQtGl6rl+kAdXDTrOo8stV0FYAL3/Hl+xJ+fh8/z9/aFX9q4Ga39yiiP07YFJgcr+IpyA406LgcCNX9WuVPNJ32dQnQzO4n3sYIgHCv2c3xJS2K7HGYXVaFvRN24HK6g5WZacp2L/GZ5mLyR2ReAVAKwdNTnCd94jGIK43WRjZDGAE4Y53umr3cYkJtMlMs7gvQ3Iegi0Gpp2JwtgYosVnxM/G0sdHJh5/v1Jecof6vKPWhf+jB+DIEtv80OEplJNLFjSpjiYrOLanp9y0K4/hRCqJRviw0JbXhLo+LiRpjqWK29IOvj3I8c8yQ9CbabtOSd5MF66hV8+LAsSf5tl7znYosKPNshP4zlwXPE26bBuX3JBGis0Pvdf26XaOguEb/5NKZWfft4MArjFLge056eu7/e0Tho46F7aU3+KsVLIh5oOfgEGgBUWAcRPX5+lcKgofvvJFB1U0dyOvnMOpKFe5ZTTb49+TlfGs4og4PpgVNrWebOAc3vniOugUsti8byHylZBD8vvQLj/gpgoEtOukGT+CL+a425Gbc3Z2KVWKnslw5Qb3wMVT+Hm+zoGMd65S5RYRBsqIT6m91blJGdsUhfDtHuuvPcIwBpuDtKGU943otOiZ+dWdzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
